title: "Danish Ahmed Darga's Portfolio"
description: "Welcome to my portfolio! Here you can find information about my projects, skills, and experiences."
remote_theme: "mmistakes/minimal-mistakes@latest"
