title: "Danish Ahmed Darga's Portfolio"
# Danish's Portfolio
description: "Welcome to my portfolio! Here you can find information about my projects, skills, and experiences."
theme: jekyll-theme-cayman
